Acme\DemoBundle\Entity\Post:
    type: entity
    table: post
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        title:
            type: text
        body:
            type: text
        date:
            type: datetime